version: '3.8'
services:
    bot:
        build: .
        restart: always
        stop_signal: SIGINT
        network_mode: host
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            SHOP_NAME: ${SHOP_NAME}
            PROTOCOLS: ${PROTOCOLS}
            TEST_PERIOD: ${TEST_PERIOD}
            PERIOD_LIMIT: ${PERIOD_LIMIT}
            ABOUT: ${ABOUT}
            RULES_LINK: ${RULES_LINK}
            SUPPORT_LINK: ${SUPPORT_LINK}
            YOOKASSA_TOKEN: ${YOOKASSA_TOKEN}
            YOOKASSA_SHOPID: ${YOOKASSA_SHOPID}
            EMAIL: ${EMAIL}
            TELEGRAM_STARS_ENABLED: ${TELEGRAM_STARS_ENABLED}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADDRESS: ${DB_ADDRESS}
            PANEL_HOST: ${PANEL_HOST}
            PANEL_GLOBAL: ${PANEL_GLOBAL}
            PANEL_USER: ${PANEL_USER}
            PANEL_PASS: ${PANEL_PASS}
            WEBHOOK_URL: ${WEBHOOK_URL}
            WEBHOOK_PORT: ${WEBHOOK_PORT}
            RENEW_NOTIFICATION_TIME: ${RENEW_NOTIFICATION_TIME}
        volumes:
            - "./goods.json:/app/goods.json"
            - "./locales:/app/locales"